paths:
  hexo: "../blog/source/_posts"
  wiki: "docs/blog/posts"
git:
  default_branch: "main"
logging:
  format: "%(log_color)s[%(levelname)s]%(reset)s %(message)s"
hooks:
  pre_commit: 
    - "src/recent_notes.py"